# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e621e726f0d3eef15d1a0e84819a61b34567366057982ef462a7c48c62da423ece4b028a242b9f264e1a9a140fd0c3920890aa1013e3ffe919b69da6a299f000

test:
  secret_key_base: 3c7d678716c75ef10ce8ef76b282c0e3699cf2ff5f74118bf222cb29e0c3199e9847bb13ed1202b7dc568e977d9dad412a94d362cb02de1b37c6add98c8658e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
